# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbank.proto\x12\x04\x62\x61nk\"&\n\x0f\x43ustomerRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x05\"L\n\x12TransactionRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x12\x11\n\tpropagate\x18\x03 \x01(\x08\"\"\n\x0f\x42\x61lanceResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x05\"\x1f\n\rEventResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xb9\x01\n\x0b\x42\x61nkService\x12\x35\n\x05Query\x12\x15.bank.CustomerRequest\x1a\x15.bank.BalanceResponse\x12\x38\n\x07\x44\x65posit\x12\x18.bank.TransactionRequest\x1a\x13.bank.EventResponse\x12\x39\n\x08Withdraw\x12\x18.bank.TransactionRequest\x1a\x13.bank.EventResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bank_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CUSTOMERREQUEST']._serialized_start=20
  _globals['_CUSTOMERREQUEST']._serialized_end=58
  _globals['_TRANSACTIONREQUEST']._serialized_start=60
  _globals['_TRANSACTIONREQUEST']._serialized_end=136
  _globals['_BALANCERESPONSE']._serialized_start=138
  _globals['_BALANCERESPONSE']._serialized_end=172
  _globals['_EVENTRESPONSE']._serialized_start=174
  _globals['_EVENTRESPONSE']._serialized_end=205
  _globals['_BANKSERVICE']._serialized_start=208
  _globals['_BANKSERVICE']._serialized_end=393
# @@protoc_insertion_point(module_scope)
